services:
  mysql:
    image: mysql:8.0
    container_name: mysql-rescate
    restart: always
    environment:
      MYSQL_DATABASE: rescate-naturaleza
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rescate
      MYSQL_PASSWORD: rescate
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: rescate-naturaleza-app
    container_name: rescate-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql_data:
